In [2]:
import numpy as np
import pandas as pd

In [3]:
sample_array = np.array([1,2,3,4,5])
print(sample_array)

[1 2 3 4 5]


In [4]:
sample_array + 3

array([4, 5, 6, 7, 8])

In [5]:
sample_array_2 = np.array([[1,2,3,4,5], [6,7,8,9,10]])

In [6]:
print(sample_array_2)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


In [7]:
sample_array_2.shape

(2, 5)

In [8]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [9]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [10]:
sample_array_2[1,2]

8

In [11]:
sample_array_2[1,2] = 0
sample_array_2


array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  0,  9, 10]])

In [12]:
sample_array

array([1, 2, 3, 4, 5])

In [13]:
sample_array[[0,1,3]]

array([1, 2, 4])

In [14]:
sample_array[[True,False,False,False,True]]

array([1, 5])

In [15]:
bool_index = sample_array % 2 == 0

In [16]:
bool_index

array([False,  True, False,  True, False])

In [17]:
sample_array[bool_index]

array([2, 4])

In [18]:
sample_array_2[ (sample_array_2 % 3 == 0) | (sample_array_2  % 5 == 0)]

array([ 3,  5,  6,  0,  9, 10])

In [19]:
sample_array[bool_index] = sample_array[bool_index] / 2

In [20]:
sample_array

array([1, 1, 3, 2, 5])

In [21]:
sample_array_2[0, 1:3]

array([2, 3])

In [22]:
sample_array_2[:, 1]

array([2, 7])

In [23]:
sample_array_2

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  0,  9, 10]])

In [24]:
sample_array_2[0, 2:]

array([3, 4, 5])

In [25]:
sample_array_3 = np.array([[1,2,3],[4,5,6],[7,8,9]])
sample_array_3

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [26]:
np.max(sample_array_3)

9

In [27]:
np.min(sample_array_3)

1

In [28]:
np.sum(sample_array_3)

45

In [29]:
np.sum(sample_array_3, axis=0)

array([12, 15, 18])

In [30]:
np.sum(sample_array_3, axis=1)

array([ 6, 15, 24])

In [31]:
sample_df = pd.DataFrame({'col1' : sample_array, 'col2' : sample_array * 2, 'col3' : ["A","B","C","D","E"] })

In [32]:
print(sample_df)

   col1  col2 col3
0     1     2    A
1     1     2    B
2     3     6    C
3     2     4    D
4     5    10    E


In [33]:
sample_df.head(3)

col1  col2 col3
0     1     2    A
1     1     2    B
2     3     6    C

In [34]:
sample_df.shape

(5, 3)

sample_df.col2

In [35]:
sample_df.col2

0     2
1     2
2     6
3     4
4    10
Name: col2, dtype: int32

In [36]:
df_1 = pd.DataFrame({'col1' : np.array([1, 2, 3]), 'col2' : np.array(["A", "B", "C"]) })
print(df_1)

   col1 col2
0     1    A
1     2    B
2     3    C


In [37]:
df_2 = pd.DataFrame({'col1' : np.array([4, 5, 6]), 'col2' : np.array(["D", "E", "F"]) })
print(df_2)

   col1 col2
0     4    D
1     5    E
2     6    F


In [38]:
pd.concat([df_1, df_2])

col1 col2
0     1    A
1     2    B
2     3    C
0     4    D
1     5    E
2     6    F

In [39]:
df_3 = pd.DataFrame({'col2' : np.array(["A", "B", "C"]), 'col3' : np.array(["あ", "い", "う"]) })
print(df_3)

  col2 col3
0    A    あ
1    B    い
2    C    う


In [42]:
pd.merge(df_1, df_3, on='col2', how='left')

col1 col2 col3
0     1    A    あ
1     2    B    い
2     3    C    う

In [43]:
sample_df.col2

0     2
1     2
2     6
3     4
4    10
Name: col2, dtype: int32

In [44]:
sample_df.shape

(5, 3)

In [45]:
sample_df.iloc[0, 2]

'A'

In [53]:
sample_df.iloc[[0,2,3],2]

0    A
2    C
3    D
Name: col3, dtype: object

In [47]:
sample_df

col1  col2 col3
0     1     2    A
1     1     2    B
2     3     6    C
3     2     4    D
4     5    10    E

In [54]:
sample_df.iloc[:, 2]

0    A
1    B
2    C
3    D
4    E
Name: col3, dtype: object

In [55]:
sample_df.iloc[:, 2] = ["F", "G", "H", "I", "J"]
print(sample_df)

   col1  col2 col3
0     1     2    F
1     1     2    G
2     3     6    H
3     2     4    I
4     5    10    J


In [59]:
sample_df.iloc[:, 2]

0    F
1    G
2    H
3    I
4    J
Name: col3, dtype: object

In [62]:
sample_df.loc[:,'col2']

0     2
1     2
2     6
3     4
4    10
Name: col2, dtype: int32

In [63]:
sample_df.query('index == 0')

col1  col2 col3
0     1     2    F

In [64]:
sample_df.query('col3 == "F" | col3 == "G"')

col1  col2 col3
0     1     2    F
1     1     2    G

In [65]:
bool_index = sample_df['col1'] % 2 == 0 # col1 が偶数の行のみTrueになる
print(bool_index)

0    False
1    False
2    False
3     True
4    False
Name: col1, dtype: bool


In [66]:
sample_df[bool_index] 

col1  col2 col3
3     2     4    I

In [73]:
sample_df.sort_values(by='col2', ascending=False)

col1  col2 col3
4     5    10    J
2     3     6    H
3     2     4    I
0     1     2    F
1     1     2    G

In [77]:
print(np.random.randint(1,5,10))
print(np.random.choice(['A','B'], 10))

[1 2 3 3 1 2 3 2 1 3]
['B' 'A' 'A' 'B' 'A' 'A' 'A' 'A' 'B' 'A']


In [75]:
sample_df_2 = pd.DataFrame({'length' : np.array([4, 2, 1, 2, 2, 1, 2, 4, 2, 2]), 'species' : np.array(['B', 'A', 'A', 'B', 'A', 'B', 'A', 'B', 'B', 'B']) })

In [76]:
sample_df_2

length species
0       4       B
1       2       A
2       1       A
3       2       B
4       2       A
5       1       B
6       2       A
7       4       B
8       2       B
9       2       B

In [78]:
sample_df_2.groupby('species').mean()

length
species        
A          1.75
B          2.50

In [79]:
sample_df.values

array([[1, 2, 'F'],
       [1, 2, 'G'],
       [3, 6, 'H'],
       [2, 4, 'I'],
       [5, 10, 'J']], dtype=object)