In [1]:
import numpy as np
import pandas as pd

In [2]:
sample_array = np.array([[1,1,1], [1,1,1]])

In [3]:
sample_array

array([[1, 1, 1],
       [1, 1, 1]])

In [6]:
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [7]:
array1 = np.zeros((3,3))

In [8]:
array1[0,0] = 1

In [9]:
array1[1,1] = 1

In [10]:
array1[2,0] = 1

In [11]:
array1

array([[1., 0., 0.],
       [0., 1., 0.],
       [1., 0., 0.]])

In [12]:
X = np.arange(16) # 0~15 までの順に並んだ行列
X.shape = (4,4) # 行列を4行4列に変換
X

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [16]:
X[2, :]

array([ 8,  9, 10, 11])

In [24]:
X[:2, 2:]

array([[2, 3],
       [6, 7]])

In [25]:
dice_numbers = np.array([[5, 2, 1],[5, 6, 1],[2, 4, 1],[3, 2, 5],[5, 2, 3]])
dice_numbers

array([[5, 2, 1],
       [5, 6, 1],
       [2, 4, 1],
       [3, 2, 5],
       [5, 2, 3]])

In [27]:
np.average(dice_numbers)

3.1333333333333333

In [28]:
np.average(dice_numbers, axis = 0)

array([4. , 3.2, 2.2])

In [29]:
np.average(dice_numbers, axis = 1)

array([2.66666667, 4.        , 2.33333333, 3.33333333, 3.33333333])

In [34]:
bool_index = dice_numbers % 2 != 0

In [35]:
dice_numbers[bool_index]

array([5, 1, 5, 1, 1, 3, 5, 5, 3])

In [36]:
dice_numbers = dice_numbers[bool_index] * 2

In [37]:
dice_numbers

array([10,  2, 10,  2,  2,  6, 10, 10,  6])

In [38]:
dice_numbers = np.array([[5, 2, 1],[5, 6, 1],[2, 4, 1],[3, 2, 5],[5, 2, 3]])
dice_numbers

array([[5, 2, 1],
       [5, 6, 1],
       [2, 4, 1],
       [3, 2, 5],
       [5, 2, 3]])

In [39]:
bool_index = dice_numbers % 2 != 0

In [40]:
dice_numbers[bool_index] = dice_numbers[bool_index] * 2

In [41]:
dice_numbers

array([[10,  2,  2],
       [10,  6,  2],
       [ 2,  4,  2],
       [ 6,  2, 10],
       [10,  2,  6]])